name: Setup, Build and Deploy
on:
  push:
    branches:
      - main
jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3
      - name: 🔑 Create $HOME/private
        run: |
          mkdir $HOME/private
      - name: 🔑 Resolve firebase.json
        env:
          FIREBASE_SECRET_ENCRYPT: ${{ secrets.FIREBASE_SECRET_ENCRYPT }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$FIREBASE_SECRET_ENCRYPT" \
          --output $HOME/private/firebaseconfig.tar firebaseconfig.tar.gpg
          tar xvf $HOME/private/firebaseconfig.tar
      - name: ⬆️ Upload firebase config
        uses: actions/upload-artifact@v3
        with:
          name: firebaseconfig
          path: $HOME/private

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev
    needs: setup
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3
      - name: ⬇️ Download firebase config
        uses: actions/download-artifact@v3
        with:
          name: firebaseconfig
          path: $HOME/private
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          channel: "stable"
          cache: true
      - name: 📦 Install Dependencies
        run: |
          flutter pub get
      - name: 🛠️ Build the application
        env:
          ANDROID_API_KEY: ${{ secrets.ANDROID_API_KEY }}
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
          IOS_API_KEY: ${{ secrets.IOS_API_KEY }}
          IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
          MACOS_API_KEY: ${{ secrets.MACOS_API_KEY }}
          MACOS_APP_ID: ${{ secrets.MACOS_APP_ID }}
          WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          WEB_APP_ID: ${{ secrets.WEB_APP_ID }}
          WINDOWS_API_KEY: ${{ secrets.WINDOWS_API_KEY }}
          WINDOWS_APP_ID: ${{ secrets.WINDOWS_APP_ID }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        run: flutter build web --dart-define=ANDROID_API_KEY="$env:ANDROID_API_KEY"
          --dart-define=ANDROID_APP_ID="$env:ANDROID_APP_ID"
          --dart-define=IOS_API_KEY="$env:IOS_API_KEY" 
          --dart-define=IOS_APP_ID="$env:IOS_APP_ID" 
          --dart-define=MACOS_API_KEY="$env:MACOS_API_KEY" 
          --dart-define=MACOS_APP_ID="$env:MACOS_APP_ID" 
          --dart-define=WEB_API_KEY="$env:WEB_API_KEY" 
          --dart-define=WEB_APP_ID="$env:WEB_APP_ID" 
          --dart-define=WINDOWS_API_KEY="$env:WINDOWS_API_KEY" 
          --dart-define=WINDOWS_APP_ID="$env:WINDOWS_APP_ID" 
          --dart-define=MESSAGING_SENDER_ID="$env:MESSAGING_SENDER_ID" 
          -t lib/main.dart
      - name: ⬆️️ Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build/web

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - name: 📚 Checkout repo
        uses: actions/checkout@v3
      - name: ⬇️ Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build/web
      - name: ⬇️ Download firebase config
        uses: actions/download-artifact@v3
        with:
          name: firebaseconfig
          path: $HOME/private
      - name: 🎯 Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEUS_AGENDA }}
          channelId: live
          projectId: teus-agenda
          workingDirectory: $HOME/private